import {
  User,
  UserCitizenship,
  UserCity,
  UserDisability,
  UserMartialStatus,
} from '../user.typings';

export const AUTO_GENERATED_USER_DATA: User = {
  actualResidenceAddress: 'Papanina street',
  actualResidenceCity: UserCity.Minsk,
  birthDate: new Date('2002-10-02'),
  citizenship: UserCitizenship.Kazahstan,
  conscript: true,
  dateOfIssue: new Date('2005-11-13'),
  disability: UserDisability.DotaPlusPlayer,
  firstName: 'Egor',
  id: null,
  identificationNumber: '666777691408HH',
  issuedBy: 'Nate higgas',
  lastName: 'Sasim',
  martialStatus: UserMartialStatus.Single,
  middleName: 'Sergeevich',
  monthlyIncome: 750,
  passportNumber: '8800555',
  passportSeries: 'MP',
  pensionary: false,
  placeOfBirth: 'Minsk',
  email: 'egorsasim@mail.ru',
  homePhoneNumber: '+375443451718',
  mobilePhoneNumber: '375443451718',
  workPlace: 'jenti',
  workPosition: 'Dungeon master',
};
